language: node_js
node_js: lts/*
branches:
  only:
    - master
script: echo “Deploy!!”
install: npm install -g firebase-tools
after_success: firebase deploy — project andor-extended — token $FIREBASE_TOKEN.