language: node_js
node_js: lts/*
branches:
  only:
    - master
script: echo “Deploy!!”
install: npm install -g firebase-tools && npm --prefix hosting install
after_success: firebase deploy --only hosting --project andor-extended